[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
via_ir = true
optimizer = true
optimizer_runs = 20000
evm_version = "cancun"
libraries = ["src/TransDeployer.sol:TransDeployer:0xB9666C67D32EdB2D8d759593300A4B500E3b938C"]
ffi = true
metadata = { useLiteralContent = false, bytecodeHash = "ipfs", appendCBOR = true }

[profile.default.outputSelection]
"*" = { "*" = ["evm.bytecode", "evm.deployedBytecode", "devdoc", "userdoc", "metadata", "abi"] }

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

[fmt]
line_length = 100
number_underscore = "thousands"
sort_imports = true
tab_width = 4
